/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItemInterface } from "./components/app-bar/app-bar";
import { MenuItemInterface as MenuItemInterface1 } from "./components/web-list/web-list";
export namespace Components {
    interface AppBar {
        /**
          * The middle name
         */
        "items": MenuItemInterface[];
        /**
          * The first name
         */
        "name": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebButton {
        /**
          * Header name
         */
        "name": string;
    }
    interface WebList {
        /**
          * List of items to show
         */
        "items": MenuItemInterface[];
        /**
          * Header name
         */
        "name": string;
    }
}
declare global {
    interface HTMLAppBarElement extends Components.AppBar, HTMLStencilElement {
    }
    var HTMLAppBarElement: {
        prototype: HTMLAppBarElement;
        new (): HTMLAppBarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWebButtonElement extends Components.WebButton, HTMLStencilElement {
    }
    var HTMLWebButtonElement: {
        prototype: HTMLWebButtonElement;
        new (): HTMLWebButtonElement;
    };
    interface HTMLWebListElement extends Components.WebList, HTMLStencilElement {
    }
    var HTMLWebListElement: {
        prototype: HTMLWebListElement;
        new (): HTMLWebListElement;
    };
    interface HTMLElementTagNameMap {
        "app-bar": HTMLAppBarElement;
        "my-component": HTMLMyComponentElement;
        "web-button": HTMLWebButtonElement;
        "web-list": HTMLWebListElement;
    }
}
declare namespace LocalJSX {
    interface AppBar {
        /**
          * The middle name
         */
        "items"?: MenuItemInterface[];
        /**
          * The first name
         */
        "name"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebButton {
        /**
          * Header name
         */
        "name"?: string;
    }
    interface WebList {
        /**
          * List of items to show
         */
        "items"?: MenuItemInterface[];
        /**
          * Header name
         */
        "name"?: string;
    }
    interface IntrinsicElements {
        "app-bar": AppBar;
        "my-component": MyComponent;
        "web-button": WebButton;
        "web-list": WebList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-bar": LocalJSX.AppBar & JSXBase.HTMLAttributes<HTMLAppBarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "web-button": LocalJSX.WebButton & JSXBase.HTMLAttributes<HTMLWebButtonElement>;
            "web-list": LocalJSX.WebList & JSXBase.HTMLAttributes<HTMLWebListElement>;
        }
    }
}
